### ISSUE TITLE
DFCxx.Polynomial2AddInt2MulInt3Asap falling

### ISSUE THREAD

**Issue by ssmolov** [ispras/utopia-hls#32]
I've built the project as follows (sorry for absolute paths):
```
rm -rf build

cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH="/home/ssedai/sources/circt.git/build;/home/ssedai/sources/circt.git/llvm/build" -DSRC_FILES="~/projects/utopia-hls/examples/polynomial2/polynomial2.cpp" -DBUILD_TESTS=ON

cmake --build build
```
After that I run `build/test/utest` and receive the following error:
```
[==========] Running 17 tests from 1 test suite.

[----------] Global test environment set-up.

[----------] 17 tests from DFCxx

[ RUN      ] DFCxx.Polynomial2AddInt2MulInt3Asap

/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = llvm::raw_fd_ostream*; _Alloc = std::allocator<llvm::raw_fd_ostream*>; std::vector<_Tp, _Alloc>::reference = llvm::raw_fd_ostream*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

./tests-run.sh: line 5: 65724 Aborted                 (core dumped) build/test/utest
```

**Comment by Muxianesty** [comment]
Looked into it: `compile`-method which is used to translate a kernel accepts a `vector` of `string` output files' paths and **assumes** that the `vector` is of the same size as the number of all possible output formats (with empty strings for excluded output formats). Normally `main.cpp` is responsible for creating a valid vector so general use of Utopia HLS doesn't fail, but the tests still use the old assumption of a single output format (SystemVerilog), so a single element `vector` is created, which fails.

I can see several ways of fixing that:
* We can change all the tests to create a valid size vector, but every time we change the order in which output files paths' are specified, we need to change all tests as well. This option makes the `compile` method a "Utopia HLS kernel level"-method rather than "user level"-method.
* We can add a new overload for the `compile`-method wrapper to accept an `unordered_map<unsigned, string>` of paths rather than a `vector` and make all tests use this implementation. Not only this might fix an issue, this also makes `compile`-method a "user level"-method, but I am not sure this is actually good.

**Comment by ssmolov** [comment]
Fixed.
